blank_issues_enabled: true
contact_links:
  - name: Commercial support?
    url: https://committed.io/contact
    about: If you want to contact us about our commercial support
  - name: Security issue?
    url: https://committed.io/contact
    about: Please report security vulnerabilities here.
