name: Build docs

on:
  push:
    branches: [$default-branch]
    paths:
      - "package.json"
      - "package-lock.json"
      - "gatsby-config.js"
      - "docs/**"

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install node modules dependencies
        run: npm ci

      - name: Build site
        run: npm exec -c 'gatsby build'
