name: Check PR

on:
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install node modules dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check --if-present

      # You may need to build common libraries on order for lint to be available
      # - name: Build
      #   run: npm run build:lib --if-present

      - name: Cache eslint
        uses: actions/cache@v2
        env:
          cache-name: eslint
        with:
          path: "**/.eslintcache"
          key: ${{ runner.os }}-${{ env.cache-name }}-$${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Lint
        run: npm run lint:check --if-present

      # You may need additional packages for testing
      # - name: Install apt packages
      #   run: sudo apt update && sudo apt-get -y --no-recommends install <package>

      - name: Test
        run: npm test --if-present

      - name: Cache sonar
        uses: actions/cache@v2
        env:
          cache-name: sonar
        with:
          path: ~/.sonar
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}

      - name: Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR: ${{ github.event.number }}
        run: npm run sonar --if-present
